language: python
sudo: false
cache: pip
python:
- '3.5'
fail_fast: true
before_install:
    - pip install pycodestyle
install: "pip install -r requirements.txt"
script:
    - pycodestyle blinkenlights.py
